In [1]:
#Команды по библиотеке numpy
#Create array from list

import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
print(type(nums_array))


<class 'numpy.ndarray'>


In [2]:
#Create 2-d array

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1,row2,row3])
nums_2d.shape

(3, 3)

In [3]:
#Create array

nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [5]:
#Create array and define step (3-d parameter)

nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [7]:
#Ones method

ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#The eye method

eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#Random method (normal distr)

normal_random = np.random.randn(4,5)
print(normal_random)

[[ 1.40992239 -0.1288839   1.28015859 -1.0560056  -0.34885488]
 [-0.17935048  0.48595777 -1.03889761 -2.12579171 -1.01410292]
 [ 0.36452516 -0.26150519 -0.67304663 -2.06566778  0.36943484]
 [-0.30186171  0.46632115  0.59504514  0.84967767  0.27205442]]


In [10]:
#Random integers from ... to (! the upper number is not included i.e. for 50 it is necessary write 50+1 (51)

integer_random = np.random.random_integers(5,50,6)
print(integer_random)

[13 38 34  7 35 20]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27684\1689963911.py:3: DeprecationWarning: This function is deprecated. Please call randint(5, 50 + 1) instead
  integer_random = np.random.random_integers(5,50,6)


In [11]:
#Reshaping and slicing

s = np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(s[1])

print(s[1:4])

print(s[:5])

2
[2 3 4]
[1 2 3 4 5]


In [13]:
print(nums_2d)

print(nums_2d[:2,:])

print(nums_2d[1:,1:])

[[10 12 13]
 [45 32 16]
 [45 32 16]]
[[10 12 13]
 [45 32 16]]
[[32 16]
 [32 16]]
